### ISSUE TITLE
Russian ru_ru language file

### ISSUE THREAD

**Issue by kellixon** [Tiviacz1337/Travellers-Backpack#1]
MC 1.12.2. TravellersBackpack 0.0.6a.
[ru_ru.zip](https://github.com/Tiviacz1337/Travellers-Backpack/files/3176029/ru_ru.zip)

**Comment by Tiviacz1337** [comment]
Thanks for it. It'll be available in next update

**Comment by Tiviacz1337** [comment]
New version of mod released - you can post updated lang file here

**Comment by kellixon** [comment]
MC 1.12.2. TravellersBackpack 0.1.1a.
[ru_ru.zip](https://github.com/Tiviacz1337/Travellers-Backpack/files/3198978/ru_ru.zip)

**Comment by Tiviacz1337** [comment]
For any more lang file updates, create pull request.
