### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by runescapejon** [Tiviacz1337/Travellers-Backpack#101]
*How to reproduce*
You need 2 backpacks
Step one, wear backpack. it doesnt need anything in it or whatever its just there. 
Step 2: open backpack(not being worn) and put dupe item inside.
Step 3: Move backpack out of hotbar.
Step 4: Take Dupe item out.
step 5: Exit inventory.
Step 6: Open backpack (not being worn) and see that the item will still be in there. but alsi in your inventory

Video guide:
https://mega.nz/file/CQElXYYJ#kd2iHtq1cUuxpy72QoOqqLsiHNbtfJT59vPENdfnAZ0

Version i am running on ....
Travellers backpack: 1.12.2-1.0.23.23
Forge: 1.12.2 - 14.23.5.2847

**Comment by runescapejon** [comment]
Yet another duplication method.

Just right click and drop at the same time and your able to duplicate the backpack items. Since the gui is still up then pick up the drop backpack and then you'll able to then have the items in the actual backpack.

**Comment by Z-Tunic** [comment]
> 
> 
> Yet another duplication method.
> 
> Just right click and drop at the same time and your able to duplicate the backpack items. Since the gui is still up then pick up the drop backpack and then you'll able to then have the items in the actual backpack.

Can confirm that this dupe method works. Should force-close the GUI if the slot that the Backpack was in is moved or removed by any means.
