### ISSUE TITLE
[Suggestion] Moveable HUD & Adding more Tool Swap Spots. *The Green Icons*

### ISSUE THREAD

**Issue by Z-Tunic** [Tiviacz1337/Travellers-Backpack#104]
Currently the HUD appears in the lower right corner of your screen with no way of moving it around Could there be a config option to move the HUD around via X & Y co?

I noticed that there's only 2 spots for swapping tools around. Could there be a config option to increase the amount of Tool Swap Slots? Looking at the GUI it looks like it can go to a max of 6 slots if wanting to keep it within the current GUI space. These extra slots could be unlocked with an craftable item of some sorts. A Travellers' Hook Latch?

**Comment by Tiviacz1337** [comment]
Added option to move HUD
