### ISSUE TITLE
[Bug]Backpack disappears if equipped on secondary hand and right click.

### ISSUE THREAD

**Issue by mzldh** [Tiviacz1337/Travellers-Backpack#11]
If backpack is equipped on shield hand, right clicking would make the backpack disappear. 
mod version: TravellersBackpack-1.12.2-0.1.3a
forge version: 14.23.5.2837
minecraft version: 1.12.2

**Comment by mzldh** [comment]
Note, bug is still peasant in  TravellersBackpack-1.12.2-0.1.4a

**Comment by Tiviacz1337** [comment]
Fixed in dev 0.1.5a

**Comment by mzldh** [comment]
Glad it’s been taken care of, I’ve lost 16 iron blocks because of it...
