### ISSUE TITLE
Hose unable to switch tanks, disappears if held in off-hand and right-clicked

### ISSUE THREAD

**Issue by themotorhead30** [Tiviacz1337/Travellers-Backpack#13]
I'm unable to switch the tank the hose uses, and right-clicking with the hose in your off-hand, it disappears.

**Comment by Tiviacz1337** [comment]
To switch hose tanks you firstly have to assign it to wearing backpack and then click N key by default (Configurable in controls) I'll try to fix off hand bug asap
