### ISSUE TITLE
Dupe bug on pick up backpack directly from ground

### ISSUE THREAD

**Issue by FabioZumbi12** [Tiviacz1337/Travellers-Backpack#14]
Hi,

Good to see this MOD updated to 1.12.2.

When using on sponge, with plugins, we can use block break events to listen and cancel block if needed.

All is working fine at this point when try to break a backpack on protected areas, but when i hold shift and click, we can worn the backpack, but the bp still on the location! This allow us to dupe any backpacks we want.

I have two backpacks on my hotbar and i have shift clicked, and weared the backpack:
![image](https://user-images.githubusercontent.com/5833818/58745332-050ef200-8426-11e9-9395-943f86c3f292.png)

The backpack still on ground, and i have worn a copy:
![image](https://user-images.githubusercontent.com/5833818/58745335-12c47780-8426-11e9-87ed-f7ad577e0239.png)

Now i have 3 on my inventory, and the original still on ground:
![image](https://user-images.githubusercontent.com/5833818/58745345-32f43680-8426-11e9-81f2-16ca7b06545b.png)
If i repeat the process, i can get infinite backpacks, and the items inside the backpacks will be dupped too.

I have disabled this option for now but i want to use on future!!

**Comment by Tiviacz1337** [comment]
Try with 0.1.6a, not sure if it will work now though

**Comment by FabioZumbi12** [comment]
Ty, i'll try when i home ^^
