### ISSUE TITLE
Backpack doesnt exist

### ISSUE THREAD

**Issue by TheDreadnaught7** [Tiviacz1337/Travellers-Backpack#15]
Put this mod in my server on beastnode and the backpack is capable of being crafted however basically doesnt exist. using creative I can see that the tank and sleeping bag have textures and an icon to grab, the backpack is an invisible item in the creative menu that has a description and thats it. I cannot use it and would like to. Any help would be great

**Comment by Tiviacz1337** [comment]
Could you provide info about your mod version, give some screenshots or any console log?

**Comment by TheDreadnaught7** [comment]
I am using the TravellersBackpack-1.12.2-0.1.5a.jar I have used everything above TravellersBackpack-1.12.2-0.0.9a.jar. This is what i see in the game when trying to get the backpack and if i use give to give myself it.
![2019-06-03_17 45 32](https://user-images.githubusercontent.com/51340186/58836743-a618cb00-8627-11e9-8164-80685f65329c.png)
![2019-06-03_17 45 38](https://user-images.githubusercontent.com/51340186/58836744-a618cb00-8627-11e9-8acd-d9eb2ac4a589.png)
![2019-06-03_17 45 41](https://user-images.githubusercontent.com/51340186/58836745-a618cb00-8627-11e9-8ac4-0aed05ffd3fe.png)

**Comment by Tiviacz1337** [comment]
Could you give me texture pack, shaders if you use and mod list?

**Comment by TheDreadnaught7** [comment]
No problem. I use the following texture packs and mods. Haven't run any shaders for a bit until i optimize certain things.
![image](https://user-images.githubusercontent.com/51340186/58904221-13cf0080-86d5-11e9-98f7-2fe1bccb2c86.png)
![image](https://user-images.githubusercontent.com/51340186/58904236-1f222c00-86d5-11e9-9e0c-768543ae626c.png)
![image](https://user-images.githubusercontent.com/51340186/58904249-28ab9400-86d5-11e9-90e3-0b9c718517e7.png)
Currently only using the 64 bit texture packs, planning on going to 128 when i can optimize the server

**Comment by Tiviacz1337** [comment]
Would it be a problem for you to upload your mods folder with currently used texturepack and send link to me by dm?

**Comment by TheDreadnaught7** [comment]
That wouldnt be a problem at all. I actually have them all set up in a dropbox for people in my discord who come and play

**Comment by Tiviacz1337** [comment]
Add me on the discord: Tiviacz1337 or send dm on curseforge

**Comment by TheDreadnaught7** [comment]
I need your # number and then ill add you and link you the packs we have. Ill add you on discord once i get  the message.

**Comment by Tiviacz1337** [comment]
Here: #1878

**Comment by Tiviacz1337** [comment]
If someone is experiencing the same issue, update optifine
