### ISSUE TITLE
Crash when referring to the backpack

### ISSUE THREAD

**Issue by kellixon** [Tiviacz1337/Travellers-Backpack#16]
MC 1.12.2. TravellersBackpack 0.1.5a. About 15-20 crashes a couple of hours. Without mod VanillaFix impossible to play.
[crash-2019-06-07_23.10.36-client.txt](https://github.com/Tiviacz1337/Travellers-Backpack/files/3267436/crash-2019-06-07_23.10.36-client.txt)

**Comment by Tiviacz1337** [comment]
When does it happen?

**Comment by kellixon** [comment]
In backpack put an 2 tool in slots under them. Pressed the shift key, scrolled the mouse wheel went crashes.

**Comment by Tiviacz1337** [comment]
Tools are from vanilla or mod?

**Comment by kellixon** [comment]
Vanilla.

**Comment by Tiviacz1337** [comment]
Issue should be fixed in 0.1.6a, if it still persists, write here.

**Comment by kellixon** [comment]
Crashes are gone, thanks for the quick solution!
