### ISSUE TITLE
Dupe Bug 

### ISSUE THREAD

**Issue by jmc529** [Tiviacz1337/Travellers-Backpack#17]
If you shift click an emptied bucket, close the backpack, and then reopen the backpack you will see the same buckets. In case it matters, I am using mouse tweaks.
![shift-click-bug](https://user-images.githubusercontent.com/9061382/59140645-89a1c900-896e-11e9-8b3c-dc71c40c5833.png)

**Comment by Tiviacz1337** [comment]
It will be fixed in next update

**Comment by Tiviacz1337** [comment]
Bug should be fixed in 0.1.6a, because bucket slots doesn't save contents anymore. Gonna keep this issue open for a few days anyway

**Comment by Tiviacz1337** [comment]
Closing this issue, if problem exsists make another
