### ISSUE TITLE
Integration request: TConstruct

### ISSUE THREAD

**Issue by jmc529** [Tiviacz1337/Travellers-Backpack#19]
When using tools it would be nice if you could cycle through one tool instead of the required three. Also, it would be nice if TConstruct tools were registered for use as well.

**Comment by P3rf3ctXZer0** [comment]
I love this idea - I have been wondering about the best way to fix tools on the fly.

**Comment by Tiviacz1337** [comment]
Added compat in latest version, not sure it will work though, test it out

**Comment by jmc529** [comment]
It seems to work for me, thanks!
