### ISSUE TITLE
Polish pl_pl language file

### ISSUE THREAD

**Issue by Speedek77** [Tiviacz1337/Travellers-Backpack#2]
Im create polish language for this mod 
[pl_PL.zip](https://github.com/Tiviacz1337/Travellers-Backpack/files/3181139/pl_PL.zip)

**Comment by Tiviacz1337** [comment]
Thanks for it 👍

**Comment by Tiviacz1337** [comment]
New version of mod released - you can post updated lang file here

**Comment by Speedek77** [comment]
[pl_pl.zip](https://github.com/Tiviacz1337/Travellers-Backpack/files/3233790/pl_pl.zip)

**Comment by Tiviacz1337** [comment]
For any more lang file updates, create pull request.

**Comment by Speedek77** [comment]
Im make Upgrade file polish language 


[pl_pl.zip](https://github.com/Tiviacz1337/Travellers-Backpack/files/3315613/pl_pl.zip)
