### ISSUE TITLE
Backpack makes the World Unuseble

### ISSUE THREAD

**Issue by Jannik24** [Tiviacz1337/Travellers-Backpack#20]
If I fill a Fluid in the Backpack and then Game Freeze and Crash it I have a Crash Report
[crash-2019-06-14_21.26.32-client.txt](https://github.com/Tiviacz1337/Travellers-Backpack/files/3291987/crash-2019-06-14_21.26.32-client.txt) after Crash I joined again the World it Crashes Instantly

**Comment by Tiviacz1337** [comment]
What fluid it was? Was backpack on the ground, in hand or worn?

**Comment by Jannik24** [comment]
Milk and in all Position Crashes it was yet in the Hand

**Comment by Tiviacz1337** [comment]
Which version of mod are you using?

**Comment by Jannik24** [comment]
The beweist 16a

**Comment by Tiviacz1337** [comment]
Were you on server or just singleplayer?

**Comment by Jannik24** [comment]
Singleplayer

**Comment by Tiviacz1337** [comment]
Do you play with any mod that adds milk fluid too?

**Comment by Jannik24** [comment]
You can see in the Crash Report what Mods I using

**Comment by Tiviacz1337** [comment]
Crash should be gone in latest version

**Comment by Jannik24** [comment]
Milk Fluid has the Purple Black Texture

**Comment by Tiviacz1337** [comment]
Avoided crash for now, gonna investigate this issue

**Comment by Jannik24** [comment]
Thanks

**Comment by Jannik24** [comment]
I dont know if I close this. If the Texture Bug fixed I dont know how you message me. Yet close or if the Texture fixes then close

**Comment by Tiviacz1337** [comment]
I'll close the issue when I fix the texture problem

**Comment by Tiviacz1337** [comment]
I do not have this issue, please remove some of your mods and check which one causes this bug

**Comment by Jannik24** [comment]
I removed all my mods and Only the BP Mod is in the Folder I See it has a Texture I looking in my Modsif The Bug makes

**Comment by Tiviacz1337** [comment]
Okay

**Comment by Jannik24** [comment]
The Texture is fixed I added All my mods and it is fixed

**Comment by Tiviacz1337** [comment]
I close the issue then
