### ISSUE TITLE
[Bug] Crash when moving backpack with Portal Gun or Gravity Gun

### ISSUE THREAD

**Issue by Googie2149** [Tiviacz1337/Travellers-Backpack#26]
To replicate, place a backpack on the ground, pick it up with either the [Portal Gun](https://minecraft.curseforge.com/projects/portal-gun) or [Gravity Gun](https://minecraft.curseforge.com/projects/gravity-gun) mods, then drop it. This will crash both a single player world and crash a server, and will continue to crash when attempting to load the world back up until uninstalling the mod.

Relevant crashlog is attached, I can grab more if needed

[crash-2019-06-20_22.50.26-server.txt](https://github.com/Tiviacz1337/Travellers-Backpack/files/3312860/crash-2019-06-20_22.50.26-server.txt)

**Comment by Tiviacz1337** [comment]
Do you use latest version of the mod?

**Comment by Googie2149** [comment]
I believe so, I have the `TravellersBackpack-1.12.2-0.1.8a` file installed. I also have the latest versions of Gravity Gun, Portal Gun, and iChun Util.

**Comment by Tiviacz1337** [comment]
Issue fixed in latest version
