### ISSUE TITLE
Updated pl_pl lang file based on 1.0.19.19

### ISSUE THREAD

**Issue by Speedek77** [Tiviacz1337/Travellers-Backpack#28]
[pl_pl.zip](https://github.com/Tiviacz1337/Travellers-Backpack/files/3316634/pl_pl.zip)

**Comment by jackowski626** [comment]
I have the feeling like you just randomly decided to put Polish special characters or not where they should be

**Comment by jackowski626** [comment]
*jprdl ile literówek

**Comment by jackowski626** [comment]
[pl_pl.zip](https://github.com/Tiviacz1337/Travellers-Backpack/files/3388900/pl_pl.zip)
Corrected naming consistency, typos and other
