### ISSUE TITLE
Backpack placed on ground are deleted when you log out

### ISSUE THREAD

**Issue by voidswrath** [Tiviacz1337/Travellers-Backpack#29]
This is my version of the mod. I see it has updated, but I thought I should report it as I did not see it in the changelog.

TravellersBackpack-1.12.2-0.0.7a

When I place a backpack on the ground, put items in it, log out, log in, the backpack is invisible until you punch where it is and the items are gone. This happens on a server I have not tried client.

**Comment by Tiviacz1337** [comment]
Download beta release, problem is fixed there
