### ISSUE TITLE
Backpack deletes inventory

### ISSUE THREAD

**Issue by gostaks** [Tiviacz1337/Travellers-Backpack#3]
Hiya! Quick bug report (hope this is the right way to do this, I'm new to modded minecraft :D). I stuck my backpack on the ground and left it there while logging out, and when I logged back in the inventory was empty. I'm using the version from the 14th, if that matters.

Thanks!!

**Comment by Tiviacz1337** [comment]
Do you know how to reproduce this issue? What did you do that it happened?

**Comment by Tiviacz1337** [comment]
Fixed in future update - 0.1.0a (99% sure)

**Comment by MagicPancake** [comment]
I could see the backpack on my player at first, but I've just noticed I no longer can. I'm using 1.12.2
