### ISSUE TITLE
Potion drinking is weird

### ISSUE THREAD

**Issue by scarredFalconer** [Tiviacz1337/Travellers-Backpack#33]
Potions are only drinkable in 1 bucket amounts, so you need to craft a potion 4 times to get 1 use while using the hose to drink the potion.

**Comment by Tiviacz1337** [comment]
In my case everything works fine and potion is drinkable with amount of 250

**Comment by touhouzun** [comment]
It must be a mod conflict, but I can't find out which mod did it.

**Comment by touhouzun** [comment]
Finally found. Immersive petroleum.
