### ISSUE TITLE
Shift-clicking a placed backpack with the sleeping bag unfolded doesn't get rid of the sleeping bag

### ISSUE THREAD

**Issue by PikaDude** [Tiviacz1337/Travellers-Backpack#36]
If you place down your backpack, unfold the sleeping bag, and then shift-click to automatically pick up and equip the backpack, the sleeping bag on the ground will not be removed allowing the player to place infinite sleeping bags. Running version 1.0.19.19 of the mod.

Update: this happens in both Singleplayer and Multiplayer.

**Comment by Tiviacz1337** [comment]
- Please provide forge version, modlist

**Comment by PikaDude** [comment]
Forge version: 14.23.5.2838
Travellers backpack is the only installed mod.
