### ISSUE TITLE
Issues involving potions

### ISSUE THREAD

**Issue by NyanMC** [Tiviacz1337/Travellers-Backpack#38]
If you have more than one potion in a tank, placing multiple glass bottles will only give you a single potion. The extra potion will be voided (depends on the amount of glass bottles were inserted), and some bottles will be deleted. An example of this is if you store 4 potions in a tank, placing 4 glass bottles at the same time will void 3 of the bottles and 3/4 of the fluid. It's really difficult to explain, you'll have to experiment with it.

Another (much smaller) issue is that trying to fill a bucket with potion will void your bucket(s).

**Comment by Tiviacz1337** [comment]
https://github.com/Tiviacz1337/Travellers-Backpack/issues/31
