### ISSUE TITLE
Chinese zh_cn language file

### ISSUE THREAD

**Issue by zsn741656478** [Tiviacz1337/Travellers-Backpack#4]
https://paste.ubuntu.com/p/WXXzbZtjQR/
Chinese language.

**Comment by Tiviacz1337** [comment]
Added in future release - 0.1.0a. Thank you 👍

**Comment by Tiviacz1337** [comment]
New version of mod released - you can post updated lang file here

**Comment by zsn741656478** [comment]
https://paste.ubuntu.com/p/FMSh6BF4gT/
Based on version 0.1.1a .

This is a great mod. Thank you for your work.

**Comment by zsn741656478** [comment]
https://paste.ubuntu.com/p/8t88fMqCmb/
Based on version 0.1.7a .

**Comment by Tiviacz1337** [comment]
For any more lang file updates, create pull request.
