### ISSUE TITLE
Shulker boxes and backpacks

### ISSUE THREAD

**Issue by futurenp** [Tiviacz1337/Travellers-Backpack#44]
With vanilla shulker boxes, you cannot place a shulker box inside a shulker box.
With this mod, you can put a backpack that contains a shulker box inside of another shulker, allowing for infinite storage.
A way to fix this is not allow backpacks to be placed inside of shulker boxes

Also, as a separate config option, please add the choice if you want shulkerboxes to be stored in backpacks.

**Comment by touhouzun** [comment]
Agree. Is there any issue with immersive engineering, actually addition, and other mods' infinite storage?@Tiviacz1337 
Also, these kind of issue is just a word : матрёшка (lol)

**Comment by Tiviacz1337** [comment]
Shulker boxes cannot be put in backpacks instead
