### ISSUE TITLE
Korean ko_kr language file

### ISSUE THREAD

**Issue by yor42** [Tiviacz1337/Travellers-Backpack#5]
[ko_kr.zip](https://github.com/Tiviacz1337/Travellers-Backpack/files/3193731/ko_kr.zip)
This is korean Localization file for this mod.(based on 1.12.2 0.1.0a)
Loving your mod. Keep up the great work :)

**Comment by Tiviacz1337** [comment]
Thanks for it! 👍

**Comment by Tiviacz1337** [comment]
New version of mod released - you can post updated lang file here

**Comment by yor42** [comment]
[ko_kr.zip](https://github.com/Tiviacz1337/Travellers-Backpack/files/3200318/ko_kr.zip)
Here's Updated Language file.

**Comment by yor42** [comment]
Updated Language file based on 0.1.5a
[ko_kr.zip](https://github.com/Tiviacz1337/Travellers-Backpack/files/3239832/ko_kr.zip)

**Comment by yor42** [comment]
Korean Language file update based on 0.1.6a
[ko_kr (2).zip](https://github.com/Tiviacz1337/Travellers-Backpack/files/3271562/ko_kr.2.zip)

**Comment by yor42** [comment]
Updates Language file based on 0.1.7a is here!
finally! tinkers tool fix! thank you!
[ko_kr.zip](https://github.com/Tiviacz1337/Travellers-Backpack/files/3293899/ko_kr.zip)

**Comment by Tiviacz1337** [comment]
For any more lang file updates, create pull request.
