### ISSUE TITLE
Dupe glitch in multiplayer

### ISSUE THREAD

**Issue by futurenp** [Tiviacz1337/Travellers-Backpack#57]
When the backpack is placed on the ground, one player breaks the backpack and the other takes items out. When the backpack is broken the other players gui does not close even thought the backpack is not present.

**Comment by futurenp** [comment]
Also please fix this asap.

Thanks!

**Comment by JayaramV-Hexaware** [comment]
Confirmed as of 1.0.20.20 on minecraft 1.12.2.  You can emulate the "another player breaking the backpack" with a block breaker connected to a timer and still be able to dupe.

**Comment by Tiviacz1337** [comment]
Fixed
