### ISSUE TITLE
Spanish es_ES language file

### ISSUE THREAD

**Issue by Krawl03** [Tiviacz1337/Travellers-Backpack#6]
Hi!

Great job with the mod. I just translated the language file into spanish.
[es_ES.zip](https://github.com/Tiviacz1337/Travellers-Backpack/files/3193886/es_ES.zip)

**Comment by Tiviacz1337** [comment]
Thanks! :)

**Comment by Tiviacz1337** [comment]
New version of mod released - you can post updated lang file here

**Comment by Krawl03** [comment]
Here you have

[es_ES.zip](https://github.com/Tiviacz1337/Travellers-Backpack/files/3203060/es_ES.zip)

**Comment by Tiviacz1337** [comment]
For any more lang file updates, create pull request.
