### ISSUE TITLE
Source request

### ISSUE THREAD

**Issue by SuperScary** [Tiviacz1337/Travellers-Backpack#8]
I was requested to implement Travellers Backpacks into Heavy Inventories (https://minecraft.curseforge.com/projects/heavy-inventories?comment=45). If there's a way i could get the source code so i can implement the backpack inventory (if its not done through with CapabilityItemHandler.ITEM_HANDLER_CAPABILITY) that would be great. thanks.

**Comment by Tiviacz1337** [comment]
My backpack uses custom way of handling inventory. I'm going to push code to the GitHub in a few minutes.

**Comment by SuperScary** [comment]
are you doing it based on NBT through https://github.com/Tiviacz1337/Travellers-Backpack/blob/06d494dc09ee2424aaf71c56ecbfdc1792020e13/src/main/java/com/tiviacz/travellersbackpack/gui/inventory/IInventoryTravellersBackpack.java#L6

**Comment by SuperScary** [comment]
Took some work but I got it to work. thanks for pushing your code!

**Comment by Tiviacz1337** [comment]
That's great 👍
