### ISSUE TITLE
[Feature Request] Sleeping in the bed should set-spawn (Forge 14.23.5.2768 - MC1.12.2)

### ISSUE THREAD

**Issue by TripleSixes** [Tiviacz1337/Travellers-Backpack#87]
I noticed that the bed is only useful for skipping to morning. I was curious if you could allow these beds to set-spawn of the player. When the bed is put back in the backpack, or the player leaves with the backpack, the spawn-point should break.

Not a huge issue as I carry another bed item with me in the backpack, but it would be nice to not have to.

Just in case this is already a feature and this is a bug for me, I tested with nothing but Forge (no other mods), same behavior. 

I will say that I get notices that the bed does indeed set spawn when using Insomniacs (the anti-sleep mod), but it doesn't actually set spawn either.

**Comment by kingdom84521** [comment]
I think that is because that is NOT a  bed, that is a sleeping bag.

**Comment by TripleSixes** [comment]
> I think that is because that is NOT a bed, that is a sleeping bag.

Fair
