### ISSUE TITLE
[Bug] Crash when death if backpackDeathPlace=true

### ISSUE THREAD

**Issue by mzldh** [Tiviacz1337/Travellers-Backpack#9]
Server crashes when being killed.
After rebooting the game and re-entering the world, server crashes again when trying to interact with the back pack placed on the ground.
btw, the placed backpack won't break if it's placed by death.
Note this is not a compatibility issue with gravestone mods, the bug still exists even without grave tone mods.
mod version: TravellersBackpack-1.12.2-0.1.3a
forge version: 14.23.5.2837
minecraft version: 1.12.2
crash log:
https://pastebin.com/8EshBMaA

**Comment by mzldh** [comment]
Note, bug is still peasant in  TravellersBackpack-1.12.2-0.1.4a after testing

**Comment by mzldh** [comment]
new crash log here:
https://pastebin.com/NzpcVefg

**Comment by Tiviacz1337** [comment]
Should be fixed in the upcoming release
