### ISSUE TITLE
Copy item  label:bug 

### ISSUE THREAD

**Issue by qiujunhan** [Tiviacz1337/Travellers-Backpack#90]
I use 1.12.2 version find a serious bug, player can copy item
First you need wear a pack
Second you open a pack on you hand
Third throw away the pack on you hand
And then take the item on the GUI

**Comment by wu452148993** [comment]
https://github.com/Tiviacz1337/Travellers-Backpack/issues/73#issue-523748475 They are the same bug. @Tiviacz1337 You can charge "Travellers-Backpack\src\main\java\com\tiviacz\travellersbackpack\gui\container\ContainerTravellersBackpack.java:
if(x == currentItemIndex && !this.inv.hasTileEntity() **&& !CapabilityUtils.isWearingBackpack(this.playerInv.player))**“ to
 ”if(x == currentItemIndex && !this.inv.hasTileEntity())” to fix it. I tested it. It works

**Comment by Wichier** [comment]
I have tested and confirmed this, it's such a serious bug. Please fix this first as soon as possible, thanks. @Tiviacz1337
